/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppChatsRouteImport } from './routes/_app.chats'
import { Route as AppFRouteImport } from './routes/_app._f'
import { Route as AppFIndexRouteImport } from './routes/_app._f.index'
import { Route as AppChatsIdRouteImport } from './routes/_app.chats.$id'
import { Route as AppFSpacesRouteImport } from './routes/_app._f.spaces'
import { Route as AppFItemsIdRouteImport } from './routes/_app._f.items.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppFRoute = AppFRouteImport.update({
  id: '/_f',
  getParentRoute: () => AppRoute,
} as any)
const AppFIndexRoute = AppFIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFRoute,
} as any)
const AppChatsIdRoute = AppChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChatsRoute,
} as any)
const AppFSpacesRoute = AppFSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppFRoute,
} as any)
const AppFItemsIdRoute = AppFItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AppFRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/chats': typeof AppChatsRouteWithChildren
  '/spaces': typeof AppFSpacesRoute
  '/chats/$id': typeof AppChatsIdRoute
  '/': typeof AppFIndexRoute
  '/items/$id': typeof AppFItemsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/chats': typeof AppChatsRouteWithChildren
  '/spaces': typeof AppFSpacesRoute
  '/chats/$id': typeof AppChatsIdRoute
  '/': typeof AppFIndexRoute
  '/items/$id': typeof AppFItemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/_f': typeof AppFRouteWithChildren
  '/_app/chats': typeof AppChatsRouteWithChildren
  '/_app/_f/spaces': typeof AppFSpacesRoute
  '/_app/chats/$id': typeof AppChatsIdRoute
  '/_app/_f/': typeof AppFIndexRoute
  '/_app/_f/items/$id': typeof AppFItemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/chats' | '/spaces' | '/chats/$id' | '/' | '/items/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/chats' | '/spaces' | '/chats/$id' | '/' | '/items/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/_f'
    | '/_app/chats'
    | '/_app/_f/spaces'
    | '/_app/chats/$id'
    | '/_app/_f/'
    | '/_app/_f/items/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_f': {
      id: '/_app/_f'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppFRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_f/': {
      id: '/_app/_f/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppFIndexRouteImport
      parentRoute: typeof AppFRoute
    }
    '/_app/chats/$id': {
      id: '/_app/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AppChatsIdRouteImport
      parentRoute: typeof AppChatsRoute
    }
    '/_app/_f/spaces': {
      id: '/_app/_f/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AppFSpacesRouteImport
      parentRoute: typeof AppFRoute
    }
    '/_app/_f/items/$id': {
      id: '/_app/_f/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AppFItemsIdRouteImport
      parentRoute: typeof AppFRoute
    }
  }
}

interface AppFRouteChildren {
  AppFSpacesRoute: typeof AppFSpacesRoute
  AppFIndexRoute: typeof AppFIndexRoute
  AppFItemsIdRoute: typeof AppFItemsIdRoute
}

const AppFRouteChildren: AppFRouteChildren = {
  AppFSpacesRoute: AppFSpacesRoute,
  AppFIndexRoute: AppFIndexRoute,
  AppFItemsIdRoute: AppFItemsIdRoute,
}

const AppFRouteWithChildren = AppFRoute._addFileChildren(AppFRouteChildren)

interface AppChatsRouteChildren {
  AppChatsIdRoute: typeof AppChatsIdRoute
}

const AppChatsRouteChildren: AppChatsRouteChildren = {
  AppChatsIdRoute: AppChatsIdRoute,
}

const AppChatsRouteWithChildren = AppChatsRoute._addFileChildren(
  AppChatsRouteChildren,
)

interface AppRouteChildren {
  AppFRoute: typeof AppFRouteWithChildren
  AppChatsRoute: typeof AppChatsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppFRoute: AppFRouteWithChildren,
  AppChatsRoute: AppChatsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
